spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/breadj?rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: '373613'
  redis:
    host: 127.0.0.1
    password: ''
    port: 6379

# 日志文件地址，配置此属性以便 SBA 在线查看日志
logging:
  file:
    path: logs/@artifactId@
    name: ${logging.file.path}/output.log

# 生产环境关闭文档
ballcat:
  openapi:
    enabled: false
  oss:
    bucket: your-bucket-here
    endpoint: http://oss-cn-shanghai.aliyuncs.com
    access-key: your key here
    access-secret: your secret here